# Generated by Django 6.0.5 on 2026-06-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["id"], "verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["id"], "verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
    ]
