# Generated by Django 6.0.5 on 2026-06-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_course_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления"),
        ),
    ]
