# Generated by Django 6.0.5 on 2026-06-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="name",
            new_name="title",
        ),
    ]
